# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: <span>MDMORY</span>
- content: 忆往传今。
bottom_saying: Deliver MEMORY.
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: AAA
  works_url: /
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/GeniusOrIdiot
# twitter: https://twitter.com/
facebook: https://www.facebook.com/
# google: https://google.com/
weibo: http://weibo.com/mdmory

#about  timeline

#Links
links:
- name: TKL-theme
  link: https://github.com/SuperKieran/TKL
- name: Hexo
  link: https://hexo.io/
